### PR TITLE
Refactor/fix heart filling doc

### LINKED ISSUE #41: - [ ] REFACTOR: Testing Suites
- [x] REFACTOR: Javascript
- [x] REFACTOR: html
- [x] REFACTOR: CSS
  - [x] Add/remove orange class btwn Filters/Meal Plan button
  - [x] bigModal instructions + image CSS refactor
  - [x] favsButton too high
  - [x] recipeNames on small cards too far left?
  - [x] make aside + sideModal smaller
  - [x] make searchBar category dropDown better
- [x] RUN: General Linter
- [x] LINGERING QUESTIONS: 
  - [x] Are we allowed to invoke another function as argument?
- [x] ASK: Phil about our catch function
- [x] CAPTURE: Gifs for readme
- [x] FINISH: Readme

### PR DESCRIPTION
**Pull request by Daniel-OC**
## What Features are Being Added?
-None

## What is Being Refactored?
- The plus signs on individual cards now toggle blue when the recipe is added to meal plan, and back to black when it's removed
- The x's to delete meals from the meal plan are now red to make it more obvious you can get it outta there

## What Do You Need From Your Teammates?
N/A

## Any Other Notes/Questions/Problems?
Not at this time

### CODE REVIEW

File: src/scripts.js [hunk 1]
```diff
@@ -59,7 +59,24 @@ const displayCurrentRecipes = () => {
   let display = cookbook.currentRecipes;
   mainDisplay.innerHTML = '';
   display.forEach(recipe => {
-    mainDisplay.innerHTML += `
+    if (user.favoriteRecipes.includes(recipe)) {
```
Comment (alexmfritz) [inline src/scripts.js]: THANK YOU!!!

**Comment by alexmfritz** [comment]
Let's definitely figure out how to refactor this to be less code... but very happy how it looks!!!
